services:
  spb-db:
    image: redis:alpine3.21
    hostname: db.spb.arpa
    ports:
    - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
